name: CI Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    permissions:
      contents: read
    name: ${{ matrix.browser }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025]
        browser: [Chrome, Firefox, Edge, Headless]
        exclude:
          - os: ubuntu-latest
            browser: Chrome
        
    steps:
      - uses: actions/checkout@v6

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneWindows: "AUS Eastern Standard Time"

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          browser: ${{ matrix.browser }}

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: artifact_${{ matrix.os }}_${{ matrix.browser }}
          path: |
            ${{ github.workspace }}/Logs/
          if-no-files-found: warn
          compression-level: 9